# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Jan  1 10:56:40 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class GroupForm(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GroupForm.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 200))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        self.groupCb = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.groupCb.SetMinSize((150, 35))
        sizer_3.Add(self.groupCb, 2, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 10)

        self.deleteGroupBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Törlés")
        sizer_3.Add(self.deleteGroupBtn, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)

        self.groupTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.groupTf.SetMinSize((150, 35))
        sizer_4.Add(self.groupTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 10)

        self.addGroupBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        sizer_4.Add(self.addGroupBtn, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        sizer_5.Add((20, 20), 2, wx.EXPAND, 0)

        self.exitBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Kilépés")
        sizer_5.Add(self.exitBtn, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class GroupForm
