# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun Jan  2 13:51:16 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LoginForm(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LoginForm.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 250))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Felhasználónév:", style=wx.ALIGN_RIGHT)
        sizer_3.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        self.userNameTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.userNameTf.SetMinSize((150, 35))
        sizer_3.Add(self.userNameTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 10)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Jelszó:", style=wx.ALIGN_RIGHT)
        sizer_4.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        self.passwordTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.passwordTf.SetMinSize((150, 35))
        sizer_4.Add(self.passwordTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 10)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        self.loginBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Bejelentkezés")
        self.loginBtn.SetMinSize((125, 35))
        sizer_5.Add(self.loginBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 50)

        self.cancelBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Mégsem")
        self.cancelBtn.SetMinSize((125, 35))
        sizer_5.Add(self.cancelBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 30)

        self.exitBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Bezárás")
        self.exitBtn.SetMinSize((125, 35))
        sizer_2.Add(self.exitBtn, 0, wx.ALIGN_RIGHT | wx.ALL, 10)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class LoginForm
