# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed Jan 12 17:50:19 2022
#

import wx
# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainForm(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainForm.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((900, 500))
        self.SetTitle("frame")

        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.Realize()
        # Tool Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        tableBox = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(tableBox, 3, wx.EXPAND, 0)

        self.studentTbl = wx.grid.Grid(self.panel_1, wx.ID_ANY, size=(1, 1))
        self.studentTbl.CreateGrid( 1, 4 )
        tableBox.Add(self.studentTbl, 3, wx.EXPAND | wx.TOP, 10)

        manageMainBox = wx.BoxSizer(wx.VERTICAL)
        tableBox.Add(manageMainBox, 1, wx.EXPAND, 0)

        searchBox = wx.BoxSizer(wx.HORIZONTAL)
        manageMainBox.Add(searchBox, 1, wx.EXPAND | wx.TOP, 30)

        self.searchTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.searchTf.SetMinSize((150, 35))
        searchBox.Add(self.searchTf, 2, wx.LEFT | wx.TOP, 10)

        self.searchBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Keresés")
        self.searchBtn.SetMinSize((110, 35))
        searchBox.Add(self.searchBtn, 0, wx.LEFT | wx.RIGHT | wx.TOP, 10)

        fillTableBox = wx.BoxSizer(wx.HORIZONTAL)
        manageMainBox.Add(fillTableBox, 1, wx.EXPAND, 0)

        self.groupCb = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.groupCb.SetMinSize((150, 35))
        fillTableBox.Add(self.groupCb, 1, wx.LEFT | wx.TOP, 10)

        self.fillStudentsBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Diákok")
        self.fillStudentsBtn.SetMinSize((110, 35))
        fillTableBox.Add(self.fillStudentsBtn, 0, wx.LEFT | wx.RIGHT | wx.TOP, 10)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Diákok")
        manageMainBox.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        manageStudentsBox = wx.BoxSizer(wx.HORIZONTAL)
        manageMainBox.Add(manageStudentsBox, 1, wx.EXPAND, 0)

        self.saveStudentBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        self.saveStudentBtn.SetMinSize((110, 35))
        manageStudentsBox.Add(self.saveStudentBtn, 0, wx.LEFT, 5)

        self.modifyStudentBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Módosítás")
        self.modifyStudentBtn.SetMinSize((110, 35))
        manageStudentsBox.Add(self.modifyStudentBtn, 0, wx.LEFT, 5)

        self.deleteStudentBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Törlés")
        self.deleteStudentBtn.SetMinSize((110, 35))
        manageStudentsBox.Add(self.deleteStudentBtn, 0, wx.LEFT | wx.RIGHT, 5)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Csoportok")
        manageMainBox.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        manageGroupsBox = wx.BoxSizer(wx.HORIZONTAL)
        manageMainBox.Add(manageGroupsBox, 1, wx.EXPAND, 0)

        self.saveGroupBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        self.saveGroupBtn.SetMinSize((110, 35))
        manageGroupsBox.Add(self.saveGroupBtn, 0, wx.LEFT, 5)

        self.modifyGroupBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Módosítás")
        self.modifyGroupBtn.SetMinSize((110, 35))
        manageGroupsBox.Add(self.modifyGroupBtn, 0, wx.LEFT | wx.RIGHT, 5)

        self.deleteGroupBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Törlés")
        self.deleteGroupBtn.SetMinSize((110, 35))
        manageGroupsBox.Add(self.deleteGroupBtn, 0, wx.LEFT | wx.RIGHT, 5)

        self.loginLogoutBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Bejelentkezés")
        self.loginLogoutBtn.SetMinSize((110, 35))
        manageMainBox.Add(self.loginLogoutBtn, 0, wx.LEFT, 50)

        self.exitBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Kilépés")
        manageMainBox.Add(self.exitBtn, 0, wx.ALIGN_RIGHT | wx.RIGHT, 10)

        self.statusLbl = wx.StaticText(self.panel_1, wx.ID_ANY, "Status label", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.statusLbl.SetMinSize((150, 30))
        sizer_2.Add( self.statusLbl, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MainForm
