# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Jan  1 10:22:19 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class StudentForm(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: StudentForm.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 394))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Név:", style=wx.ALIGN_RIGHT)
        sizer_4.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        self.nameTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.nameTf.SetMinSize((150, 35))
        sizer_4.Add(self.nameTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Email:", style=wx.ALIGN_RIGHT)
        sizer_5.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        self.emailTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.emailTf.SetMinSize((150, 35))
        sizer_5.Add(self.emailTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Telefon:", style=wx.ALIGN_RIGHT)
        sizer_6.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        self.phoneTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.phoneTf.SetMinSize((150, 35))
        sizer_6.Add(self.phoneTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Születés:", style=wx.ALIGN_RIGHT)
        sizer_7.Add(label_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        self.bornTf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.bornTf.SetMinSize((150, 35))
        sizer_7.Add(self.bornTf, 2, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 10)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_9, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_9.Add(label_5, 1, 0, 0)

        self.groupCb = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_9.Add(self.groupCb, 2, wx.BOTTOM | wx.RIGHT | wx.TOP, 10)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)

        self.addStudentBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        sizer_8.Add(self.addStudentBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 7)

        self.modifyStudentBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Módosítás")
        sizer_8.Add(self.modifyStudentBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        self.deleteStudentBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Törlés")
        sizer_8.Add(self.deleteStudentBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        self.cancelBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Mégsem")
        sizer_8.Add(self.cancelBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_10, 1, wx.EXPAND, 0)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10.Add(sizer_11, 1, wx.EXPAND, 0)

        sizer_11.Add((20, 20), 3, wx.EXPAND, 0)

        self.exitBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Bezárás")
        sizer_11.Add(self.exitBtn, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 8)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class StudentForm
